"""initial schema

Revision ID: 34c34854e664
Revises: 
Create Date: 2026-09-23 16:51:56.553566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '34c34854e664'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=32), nullable=False),
    sa.Column('hint', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clues_answer'), 'clues', ['answer'], unique=False)
    op.create_index(op.f('ix_clues_length'), 'clues', ['length'], unique=False)
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_date', sa.Date(), nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=False),
    sa.Column('blocked_cells', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzles_puzzle_date'), 'puzzles', ['puzzle_date'], unique=True)
    op.create_table('users',
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('ACROSS', 'DOWN', name='direction'), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('start_col', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=32), nullable=False),
    sa.Column('hint', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_id', 'number', 'direction')
    )
    op.create_index(op.f('ix_lines_puzzle_id'), 'lines', ['puzzle_id'], unique=False)
    op.create_table('cell_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'row', 'col')
    )
    op.create_index(op.f('ix_cell_contributions_line_id'), 'cell_contributions', ['line_id'], unique=False)
    op.create_index(op.f('ix_cell_contributions_puzzle_id'), 'cell_contributions', ['puzzle_id'], unique=False)
    op.create_table('line_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id'),
    sa.UniqueConstraint('puzzle_id', 'user_id')
    )
    op.create_index(op.f('ix_line_assignments_line_id'), 'line_assignments', ['line_id'], unique=False)
    op.create_index(op.f('ix_line_assignments_puzzle_id'), 'line_assignments', ['puzzle_id'], unique=False)
    op.create_index(op.f('ix_line_assignments_user_id'), 'line_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_assignments_user_id'), table_name='line_assignments')
    op.drop_index(op.f('ix_line_assignments_puzzle_id'), table_name='line_assignments')
    op.drop_index(op.f('ix_line_assignments_line_id'), table_name='line_assignments')
    op.drop_table('line_assignments')
    op.drop_index(op.f('ix_cell_contributions_puzzle_id'), table_name='cell_contributions')
    op.drop_index(op.f('ix_cell_contributions_line_id'), table_name='cell_contributions')
    op.drop_table('cell_contributions')
    op.drop_index(op.f('ix_lines_puzzle_id'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_puzzles_puzzle_date'), table_name='puzzles')
    op.drop_table('puzzles')
    op.drop_index(op.f('ix_clues_length'), table_name='clues')
    op.drop_index(op.f('ix_clues_answer'), table_name='clues')
    op.drop_table('clues')
    # ### end Alembic commands ###
